name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Docker Image Build
      run: docker build --no-cache -t ${{ secrets.USERNAME }}/${{ secrets.PROJECT_NAME }} .

    - name: DockerHub Push
      run: docker push ${{ secrets.USERNAME }}/${{ secrets.PROJECT_NAME }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port : ${{ secrets.SERVER_PORT }}
        script: |
          docker stop ${{ secrets.APPLICATION_NAME }}
          docker rm ${{ secrets.APPLICATION_NAME }}
          docker rmi ${{ secrets.USERNAME }}/${{ secrets.PROJECT_NAME }}
          docker pull ${{ secrets.USERNAME }}/${{ secrets.PROJECT_NAME }}
          docker run --network=host -d -p ${{ secrets.DEPLOY_PORT }}:8080 -e TZ=Asia/Seoul --name ${{ secrets.APPLICATION_NAME }} ${{ secrets.USERNAME }}/${{ secrets.PROJECT_NAME }}
